{
 "title": "Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "count(kube_pod_info)", "legendFormat": "__auto" },
    { "expr": "kube_node_status_condition", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "USE Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(container_memory_usage_bytes / container_memory_limit_bytes) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(container_last_seen[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "etcd_server_proposals_latency_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "etcd_server_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prometheus Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "rate(prometheus_http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}